arcface: false
batchsize: 32
checkpoint: /home/toms.zinars/tomass/ReID_pipeline/vehicle_reid_repo2/vehicle_reid/model/veri+vehiclex_str1+lin256+colJit/net_19.pth
circle: false
color_jitter: true
contrast: false
cosface: false
cosine: false
data_dir: /home/toms.zinars/tomass/data
debug: false
debug_period: 100
droprate: 0.5
erasing_p: 0.5
fp16: false
gpu_ids: '0'
grad_clip_max_norm: 50.0
ins_gamma: 32
instance: false
label_smoothing: 0.0
lifted: false
linear_num: 256
lr: 0.05
mixstyle: false
model: resnet_ibn
model_subtype: default
name: veri+vehiclex_str1+lin256+colJit
nclasses: 2131
num_workers: 3
samples_per_class: 1
save_freq: 1
sphere: false
start_epoch: 20
stride: 1
total_epoch: 30
tpu_cores: -1
train_csv_path: /home/toms.zinars/tomass/data/VeRi_VehicX/VeRi+VehicX_train.csv
triplet: true
val_csv_path: /home/toms.zinars/tomass/data/VeRi_VehicX/VeRi+VehicX_val.csv
warm_epoch: 3
